# Generated by Django 4.0.6 on 2022-07-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='logo',
            field=models.ImageField(default='static/placeholder.png', upload_to='user_data/'),
        ),
    ]
