# Generated by Django 4.0.6 on 2022-08-12 16:37

import datetime
from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 12, 16, 37, 2, 563135)),
        ),
        migrations.AlterField(
            model_name='post',
            name='logo',
            field=models.ImageField(blank=True, upload_to=posts.models.get_file_path),
        ),
    ]
