# Generated by Django 4.1 on 2022-08-15 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_pub_date_alter_post_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 15, 13, 35, 19, 250584)),
        ),
    ]
